---
title: Arcadian
timezone: UTC
collections:
  pages:
    title: Pages
    output: false
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: matthanwesterneng@gmail.com
description: A place for stories to gather.
baseurl: ''
url: https://www.arcadian.blog
icon: "/assets/images/icon.png"
twitter_username: mattisnocat
github_username: mattisnocat
permalink: "/:categories/:title/"
markdown: kramdown
show_excerpts: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page/:num/"
