---
title: Arcadian
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: matthanwesterneng@gmail.com
description: A place for stories to gather.
baseurl: 
url: https://www.arcadian.blog
icon: "/assets/images/icon-512.png"
twitter_username: mattisnocat
github_username: mattisnocat
markdown: kramdown
show_excerpts: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page/:num/"
