---
title: Arcadian
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: matthanwesterneng@gmail.com
<<<<<<< HEAD
<<<<<<< HEAD
description: >- # this means to ignore newlines until "baseurl:"
  A place for stories to gather.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arcadian.blog" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon.png
twitter_username: mattisnocat
github_username:  mattisnocat
permalink: /:categories/:title/
collections:
  pages:
    permalink: /:title/

# Build settings
markdown: kramdown
show_excerpts: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page/:num/"
